name: Coding Standards

on: pull_request

jobs:
  phpcs:
    name: Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --no-interaction --no-dev --no-progress

      - name: Run PHP Code Sniffer
        run: composer run phpcs

      - name: Run PHP Code Beautifier
        run: composer run phpcbf

      - name: Run PHPStan
        run: composer run phpstan


