name: WordPress Coding Standards

on: pull_request

jobs:
  phpcs:
    name: Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --no-interaction --no-dev --no-progress

      - name: Run tests
        run: composer test
