name: Testing

on: pull_request

jobs:
  phpcs:
    name: testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.2', 'latest' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mysql
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Regenerate the autoloader files
        run: composer dump-autoload --optimize

      - name: Run tests
        run: composer test
